const purgecss = require('@fullhuman/postcss-purgecss');
module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    purgecss({
      content: ['./**/*.js', './src/**/*.jsx'],
      rejected: true,
      css: ['./src/**/*.css'],
      safelist: [
        'hover:bg-opacity-5',
        'hover:text-white',
        'lg:w-full',
        'sm:text-sm',
        'sm:h-96',
        'lg:flex',
        'lg:w-3/4',
        'lg:mt-9',
        'sm:w-9/12',
        'sm:m-auto',
        'lg:w-1/2',
        'md:w-4/5',
        'md:m-auto',
        'lg:w-1/2',
        'lg:hidden',
        'sm:w-40',
        'sm:h-40',
        'lg:block',
        'lg:w-full',
        'max-w-1/4',
        'sm:w-40',
        '-my-5 ',
        'w-1/4',
        'lg:flex-row-reverse',
        'w-3/4',
      ],
    }),
  ],
};
